### ISSUE TITLE
Turn AILL into appimaged replacement

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#182]
In an effort to unify various tools that have similar functionality, we want to unify appimaged and AppImageLauncher Lite.

Open points in AppImageLauncher Lite that need to be closed in order for it to become a suitable `appimaged` replacement.

Prio 1:
* [x] Watch more than one directory, especially the Downloads directory https://github.com/TheAssassin/AppImageLauncher/issues/77
* [x] Watch defined directory/directories on all partitions https://github.com/TheAssassin/AppImageLauncher/issues/154
* [x] Suppress desktop integration scripts in AppImages https://github.com/TheAssassin/AppImageLauncher/issues/181
* [x] ~~Naming. E.g., call AppImageLauncher Lite "appimaged 2.0" or find another name. It is not really a "Launcher"~~
* [x] Use libappimage master, not an old version. TheAssassin to define what needs to happen for that
* [x] AppImage does not get integrated, log shows no reason #183 
* [x] Get rid of frightening warning #187
* [x] After an update, no moving should be attempted #188

Prio 2:
* [x] Update fails if AppImage location is not writeable by user https://github.com/TheAssassin/AppImageLauncher/issues/186
* [x] Remove fails if AppImage location is not user writeable #190
* [x] Bundle Qt Gtk theme in AILL AppImage #199

This list will be amended as additional showstoppers are discovered.

**Comment by TheAssassin** [comment]
We're done! The upcoming 2.0 release fulfills all requested points, except for that weird rename suggestion that isn't going to happen.

The 2.1 release will then feature a redesign of the main integration dialog.

**Comment by probonopd** [comment]
To make a drop-in replacement for `appimaged`, I'd still like to see 

> We could also make this a setting at some point.

from https://github.com/TheAssassin/AppImageLauncher/pull/248 to be implemented.

**Comment by TheAssassin** [comment]
There *is* a setting. Check https://github.com/TheAssassin/AppImageLauncher/blob/master/src/shared/shared.cpp#L157. See https://github.com/TheAssassin/AppImageLauncher/commit/a67bc8fb7bdd4151cd94f2d6b7ec1109e76901ff for more information.

**Comment by probonopd** [comment]
Great. Can we make it the default?

**Comment by TheAssassin** [comment]
No. There's obvious security implications. This flag is slightly hidden for now for a reason. Let's call it an "evaluation phase", we can re-assess the situation in a few weeks.
